# Generated by Django 4.2.6 on 2023-11-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cloth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customercl",
            name="name",
        ),
        migrations.RemoveField(
            model_name="ordercl",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="ordercl",
            name="products",
        ),
        migrations.AddField(
            model_name="customercl",
            name="first_name",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customercl",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="ordercl",
            name="product",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cloth.productcl",
            ),
        ),
        migrations.AddField(
            model_name="ordercl",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ordercl",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="tagcl",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="customercl",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="productcl",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tagcl",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
