# Generated by Django 4.2.6 on 2023-10-24 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
