# Generated by Django 4.2.6 on 2023-11-13 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_alter_reviewproglang_title_lang_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
